package org.prez.springmysql.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/usuarios") // This means URL's start with /demo (after Application path)
public class UsuarioController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsuarioRepository usuarioRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String nombre,
             @RequestParam String correo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Usuario n = new Usuario();
        n.setNombre(nombre);
        n.setCorreo(correo);
        usuarioRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Usuario> getAllUsers() {
        return usuarioRepository.findAll();// This returns a JSON or XML with the users
    }
    
    @GetMapping(path = "/delete")
    public @ResponseBody
    void delete(@RequestParam int id){
        Usuario u = new Usuario();
        u.setId(id);
        
        usuarioRepository.delete(u);
    }
}
